version: '3.0'

services:

  mysql:
    image: mysql:5.7
    container_name: mdk-mysql-dev
    volumes:
      - ./docker-data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - app-network

  php:
    build:
      context: ./.docker/php
      args:
        uid: 1000
        user: runner
    container_name: mdk-php-dev
    depends_on: 
      - mysql
    volumes:
      - ./:/opt/mdk/
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/dev/entrypoint.sh:/usr/bin/entrypoint.sh
    command: /bin/bash -c "/usr/bin/entrypoint.sh"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/24
